GET http://localhost:4000/ping HTTP/1.1

###

GET http://localhost:4000/users HTTP/1.1

###
GET  http://localhost:4000/users/1e60081f-117a-4c80-a864-306b044ca3b9 HTTP/1.1

###

POST http://localhost:4000/users HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "testemail@wezz.com"
}

###
GET http://localhost:4000/posts HTTP/1.1
###
POST http://localhost:4000/post HTTP/1.1
Content-Type: application/json

{
    "userID":"1e60081f-117a-4c80-a864-306b044ca3b9",
    "text":"it's all good for now"
}